### ISSUE TITLE
Practica Seguimiento y Control

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-team-remi#1]
[PRACTICA SEGUIMIENTO Y CONTROL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-team-remi/files/10189459/PRACTICA.SEGUIMIENTO.Y.CONTROL.pdf)

**Comment by Band-hi** [comment]
@Yabin-2021
@Brisa-4
@JazminloRI
Adjunto reporte de practica correspondiente a la practica 9

**Comment by Yabin-2021** [comment]
Buen trabajo y revisado
50 %

**Comment by Band-hi** [comment]
@josealfredo79 ya está calificado Ing.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
